run:
  timeout: 5m
  go: "1.20"

issues:
  exclude-dirs:
    - vendor
    - third_party
    - testdata
    - examples
  exclude-files:
    - ".*_test\\.go$"
    - "\\.pb\\.go$"
    - "\\.gen\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: _test\.go
      text: "G404: Use of weak random number generator"
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - bodyclose
    - goconst
    - goimports
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gosec:
    excludes:
      - G104 # Audit errors not being checked
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  staticcheck:
    checks: ["all"]
  gosimple:
    checks: ["all"]
  unused:
    check-exported: false
  unparam:
    check-exported: false
  whitespace:
    multi-if: true
    multi-func: true

output:
  format: colored-line-number 