apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auto-unseal
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-auto-unseal
  namespace: vault
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-auto-unseal
  namespace: vault
subjects:
- kind: ServiceAccount
  name: vault-auto-unseal
  namespace: vault
roleRef:
  kind: Role
  name: vault-auto-unseal
  apiGroup: rbac.authorization.k8s.io 